/** @type {import('@commitlint/types').UserConfig} */
module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "build",
        "ci",
        "chore",
        "revert",
        "security",
        "deps",
      ],
    ],
    "subject-case": [2, "always", ["sentence-case", "lower-case"]],
    "body-max-line-length": [1, "always", 100],
    "scope-enum": [
      2,
      "always",
      [
        "stellar-contracts",
        "evm-contracts",
        "bridge",
        "relayer",
        "indexer",
        "api",
        "sdk",
        "frontend",
        "infra",
        "docs",
        "ci",
        "deps",
        "release",
      ],
    ],
  },
};
